In [2]:
import pandas as pd
import numpy as np


In [19]:
# DATA INPUT

file_path = "./diabetes.csv"
df = pd.read_csv(file_path)

df.head()

Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0           0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1           0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2           0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3           0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4           0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
0          0.0      5.0      18.0      15.0       1.0  0.0   9.0        4.0   
1          1.0      3.0       0.0       0.0       0.0  0.0   7.0        6.0   
2          1.0      5.0      30.0      30.0       1.0  0.0   9.0        4.0   
3          0.0      2.0       0.0       0.0       0.0  0.0  11.0        3.0   
4          0.0      2.0       3.0       0.0       0.0  0.0  11.0        5.0   

   Income  
0     3.0  
1     1.0  
2     8.0  
3     6.0  
4     4.0  

[5 rows x 22 columns]

In [20]:
df1 = pd.read_csv("./diabetes2.csv")
df1.head()

Age  Gender   BMI  SBP  DBP   FPG  Chol   Tri   HDL   LDL   ALT   BUN  \
0   26       1  20.1  119   81  5.80  4.36  0.86  0.90  2.43  12.0  5.40   
1   40       1  17.7   97   54  4.60  3.70  1.02  1.50  2.04   9.2  3.70   
2   40       2  19.7   85   53  5.30  5.87  1.29  1.75  3.37  10.1  4.10   
3   43       1  23.1  111   71  4.50  4.05  0.74  1.27  2.60  36.5  4.38   
4   36       1  26.5  130   82  5.54  6.69  3.49  0.91  3.64  69.3  3.86   

    CCR  FFPG  smoking  drinking  family_histroy  Diabetes  
0  63.8  5.40      3.0       3.0               0         0  
1  70.3  4.10      1.0       1.0               0         0  
2  61.1  4.85      3.0       3.0               0         0  
3  73.4  5.30      2.0       3.0               0         0  
4  67.5  5.53      3.0       3.0               0         0

In [21]:
df.columns

Index(['Diabetes_012', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [22]:
df1.columns

Index(['Age', 'Gender', 'BMI', 'SBP', 'DBP', 'FPG', 'Chol', 'Tri', 'HDL',
       'LDL', 'ALT', 'BUN', 'CCR', 'FFPG', 'smoking', 'drinking',
       'family_histroy', 'Diabetes'],
      dtype='object')

In [23]:
print(df['Diabetes_012'].unique())

[0. 2. 1.]


In [24]:
df['Diabetes_012'] = df['Diabetes_012'].astype(int)

In [25]:
print(df['Diabetes_012'].unique())

[0 2 1]


In [26]:
df.rename(columns={'Diabetes_012' : 'Diabetes'} , inplace=True)

In [27]:
print(df1["Diabetes"].unique())

[0 1]


In [28]:
df.rename(columns={'Sex' : 'Gender' , 'Smoker' : 'smoking'} , inplace=True)

In [29]:
df.columns

Index(['Diabetes', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'smoking',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Gender', 'Age', 'Education',
       'Income'],
      dtype='object')

In [30]:
df.head()

Diabetes  HighBP  HighChol  CholCheck   BMI  smoking  Stroke  \
0         0     1.0       1.0        1.0  40.0      1.0     0.0   
1         0     0.0       0.0        0.0  25.0      1.0     0.0   
2         0     1.0       1.0        1.0  28.0      0.0     0.0   
3         0     1.0       0.0        1.0  27.0      0.0     0.0   
4         0     1.0       1.0        1.0  24.0      0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Gender   Age  \
0          0.0      5.0      18.0      15.0       1.0     0.0   9.0   
1          1.0      3.0       0.0       0.0       0.0     0.0   7.0   
2          1.0      5.0      30.0      30.0       1.0     0.0   9.0   
3          0.0      2.0       0.0       0.0       0.0     0.0  11.0   
4          0.0      2.0       3.0       0.0       0.0     0.0  11.0   

   Education  Income  
0        4.0     3.0  
1        6.0     1.0  
2        4.0     8.0  
3        3.0     6.0  
4        5.0     4.0  

[5 rows x 22 columns]

In [31]:
df['Gender'].unique()

array([0., 1.])

In [32]:
df['Gender'] = df['Gender'].astype(int)

In [33]:
df['Gender'].unique()

array([0, 1])

In [34]:
df['Age'] = df['Age'].astype(int)

In [35]:
df['Age'].unique()

array([ 9,  7, 11, 10,  8, 13,  4,  6,  2, 12,  5,  1,  3])

In [36]:
df1['Gender'].unique()

array([1, 2])

In [37]:
df1['Gender'] = df1['Gender'].map({1 : 0 , 2 : 1})

In [38]:
df1['Gender'].unique()

array([0, 1])

In [39]:
df.head()

Diabetes  HighBP  HighChol  CholCheck   BMI  smoking  Stroke  \
0         0     1.0       1.0        1.0  40.0      1.0     0.0   
1         0     0.0       0.0        0.0  25.0      1.0     0.0   
2         0     1.0       1.0        1.0  28.0      0.0     0.0   
3         0     1.0       0.0        1.0  27.0      0.0     0.0   
4         0     1.0       1.0        1.0  24.0      0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Gender  Age  Education  \
0          0.0      5.0      18.0      15.0       1.0       0    9        4.0   
1          1.0      3.0       0.0       0.0       0.0       0    7        6.0   
2          1.0      5.0      30.0      30.0       1.0       0    9        4.0   
3          0.0      2.0       0.0       0.0       0.0       0   11        3.0   
4          0.0      2.0       3.0       0.0       0.0       0   11        5.0   

   Income  
0     3.0  
1     1.0  
2     8.0  
3     6.0  
4     4.0  

[5 rows x 22 columns]

In [40]:
df1.head()

Age  Gender   BMI  SBP  DBP   FPG  Chol   Tri   HDL   LDL   ALT   BUN  \
0   26       0  20.1  119   81  5.80  4.36  0.86  0.90  2.43  12.0  5.40   
1   40       0  17.7   97   54  4.60  3.70  1.02  1.50  2.04   9.2  3.70   
2   40       1  19.7   85   53  5.30  5.87  1.29  1.75  3.37  10.1  4.10   
3   43       0  23.1  111   71  4.50  4.05  0.74  1.27  2.60  36.5  4.38   
4   36       0  26.5  130   82  5.54  6.69  3.49  0.91  3.64  69.3  3.86   

    CCR  FFPG  smoking  drinking  family_histroy  Diabetes  
0  63.8  5.40      3.0       3.0               0         0  
1  70.3  4.10      1.0       1.0               0         0  
2  61.1  4.85      3.0       3.0               0         0  
3  73.4  5.30      2.0       3.0               0         0  
4  67.5  5.53      3.0       3.0               0         0

In [41]:
df1 = df1.astype({'smoking' : 'int' , 'drinking' : 'int'})

In [43]:
df1['drinking'].unique()

array([3, 1, 2, 4])

In [53]:
df2 = df1[df1['drinking'] != 4]

In [55]:
df2['smoking'].unique()

array([3, 1, 2])

In [57]:
df2.shape

(3415, 18)

In [58]:
df2.head()

Age  Gender   BMI  SBP  DBP   FPG  Chol   Tri   HDL   LDL   ALT   BUN  \
0   26       0  20.1  119   81  5.80  4.36  0.86  0.90  2.43  12.0  5.40   
1   40       0  17.7   97   54  4.60  3.70  1.02  1.50  2.04   9.2  3.70   
2   40       1  19.7   85   53  5.30  5.87  1.29  1.75  3.37  10.1  4.10   
3   43       0  23.1  111   71  4.50  4.05  0.74  1.27  2.60  36.5  4.38   
4   36       0  26.5  130   82  5.54  6.69  3.49  0.91  3.64  69.3  3.86   

    CCR  FFPG  smoking  drinking  family_histroy  Diabetes  
0  63.8  5.40        3         3               0         0  
1  70.3  4.10        1         1               0         0  
2  61.1  4.85        3         3               0         0  
3  73.4  5.30        2         3               0         0  
4  67.5  5.53        3         3               0         0

In [59]:
df2['smoking'] = df2['smoking'].map({1 : 1 , 2 : 1 , 3 : 0})


C:\Users\vishal ghosh\AppData\Local\Temp\ipykernel_16048\476691982.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['smoking'] = df2['smoking'].map({1 : 1 , 2 : 1 , 3 : 0})


In [60]:
df2['smoking'].unique()

array([0, 1])

In [61]:
df2['drinking'] = df2['drinking'].map({1 : 1 , 2 : 1 , 3 : 0})

C:\Users\vishal ghosh\AppData\Local\Temp\ipykernel_16048\3751635570.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['drinking'] = df2['drinking'].map({1 : 1 , 2 : 1 , 3 : 0})


In [62]:
df2['drinking'].unique()

array([0, 1])

In [63]:
df2.head()

Age  Gender   BMI  SBP  DBP   FPG  Chol   Tri   HDL   LDL   ALT   BUN  \
0   26       0  20.1  119   81  5.80  4.36  0.86  0.90  2.43  12.0  5.40   
1   40       0  17.7   97   54  4.60  3.70  1.02  1.50  2.04   9.2  3.70   
2   40       1  19.7   85   53  5.30  5.87  1.29  1.75  3.37  10.1  4.10   
3   43       0  23.1  111   71  4.50  4.05  0.74  1.27  2.60  36.5  4.38   
4   36       0  26.5  130   82  5.54  6.69  3.49  0.91  3.64  69.3  3.86   

    CCR  FFPG  smoking  drinking  family_histroy  Diabetes  
0  63.8  5.40        0         0               0         0  
1  70.3  4.10        1         1               0         0  
2  61.1  4.85        0         0               0         0  
3  73.4  5.30        1         0               0         0  
4  67.5  5.53        0         0               0         0

In [64]:
def age_to_category(age):
    if age > 18 and age < 25:
        return 1
    elif age > 24 and age < 30:
        return 2
    elif age > 29 and age < 35:
        return 3
    elif age > 34 and age < 40:
        return 4
    elif age > 39 and age < 45:
        return 5
    elif age > 44 and age < 50:
        return 6
    elif age > 49 and age < 55:
        return 7
    elif age > 54 and age < 60:
        return 8
    elif age > 59 and age < 65:
        return 9
    elif age > 64 and age < 70:
        return 10
    elif age > 69 and age < 75:
        return 11
    elif age > 74 and age < 80:
        return 12
    elif age > 80:
        return 13
    
    



In [65]:
df2['Age'] = df2['Age'].apply(age_to_category)
 

C:\Users\vishal ghosh\AppData\Local\Temp\ipykernel_16048\2309709145.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Age'] = df2['Age'].apply(age_to_category)


In [66]:
df2['Age'].unique()

array([ 2.,  5.,  4.,  6.,  7.,  3.,  8., 13.,  9., 12., 10.,  1., 11.,
       nan])

In [67]:
df1['Age'].unique()

array([26, 40, 43, 36, 46, 52, 33, 42, 37, 51, 38, 50, 53, 47, 27, 45, 55,
       34, 85, 63, 44, 30, 29, 31, 78, 39, 68, 22, 41, 54, 35, 74, 67, 49,
       56, 59, 28, 77, 72, 48, 69, 62, 32, 64, 25, 70, 57, 60, 75, 61, 76,
       66, 24, 58, 73, 65, 71, 79, 84, 80, 83, 82, 86, 93, 23, 87, 88, 81,
       90, 91])

In [77]:
count1 = (df2['Age'] == None).sum()
print(count1)

0


In [81]:
df2.replace(to_replace=np.nan, value=0, inplace=True)


C:\Users\vishal ghosh\AppData\Local\Temp\ipykernel_16048\1229338250.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.replace(to_replace=np.nan, value=0, inplace=True)


In [95]:
df.isna().sum()

Diabetes                0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
smoking                 0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Gender                  0
Age                     0
Education               0
Income                  0
dtype: int64

In [83]:
df2['Age'].unique()

array([ 2.,  5.,  4.,  6.,  7.,  3.,  8., 13.,  9., 12., 10.,  1., 11.,
        0.])

In [86]:
df3 = df2[df2['Age'] != 0]

In [87]:
df3['Age'].unique()

array([ 2.,  5.,  4.,  6.,  7.,  3.,  8., 13.,  9., 12., 10.,  1., 11.])

In [88]:
df3.head()

Age  Gender   BMI  SBP  DBP   FPG  Chol   Tri   HDL   LDL   ALT   BUN  \
0  2.0       0  20.1  119   81  5.80  4.36  0.86  0.90  2.43  12.0  5.40   
1  5.0       0  17.7   97   54  4.60  3.70  1.02  1.50  2.04   9.2  3.70   
2  5.0       1  19.7   85   53  5.30  5.87  1.29  1.75  3.37  10.1  4.10   
3  5.0       0  23.1  111   71  4.50  4.05  0.74  1.27  2.60  36.5  4.38   
4  4.0       0  26.5  130   82  5.54  6.69  3.49  0.91  3.64  69.3  3.86   

    CCR  FFPG  smoking  drinking  family_histroy  Diabetes  
0  63.8  5.40        0         0               0         0  
1  70.3  4.10        1         1               0         0  
2  61.1  4.85        0         0               0         0  
3  73.4  5.30        1         0               0         0  
4  67.5  5.53        0         0               0         0

In [89]:
df.head()

Diabetes  HighBP  HighChol  CholCheck   BMI  smoking  Stroke  \
0         0     1.0       1.0        1.0  40.0      1.0     0.0   
1         0     0.0       0.0        0.0  25.0      1.0     0.0   
2         0     1.0       1.0        1.0  28.0      0.0     0.0   
3         0     1.0       0.0        1.0  27.0      0.0     0.0   
4         0     1.0       1.0        1.0  24.0      0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Gender  Age  Education  \
0          0.0      5.0      18.0      15.0       1.0       0    9        4.0   
1          1.0      3.0       0.0       0.0       0.0       0    7        6.0   
2          1.0      5.0      30.0      30.0       1.0       0    9        4.0   
3          0.0      2.0       0.0       0.0       0.0       0   11        3.0   
4          0.0      2.0       3.0       0.0       0.0       0   11        5.0   

   Income  
0     3.0  
1     1.0  
2     8.0  
3     6.0  
4     4.0  

[5 rows x 22 columns]

In [96]:
df = df.astype({'smoking' : 'int'})


In [97]:
df.head()

Diabetes  HighBP  HighChol  CholCheck   BMI  smoking  Stroke  \
0         0     1.0       1.0        1.0  40.0        1     0.0   
1         0     0.0       0.0        0.0  25.0        1     0.0   
2         0     1.0       1.0        1.0  28.0        0     0.0   
3         0     1.0       0.0        1.0  27.0        0     0.0   
4         0     1.0       1.0        1.0  24.0        0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Gender  Age  Education  \
0          0.0      5.0      18.0      15.0       1.0       0    9        4.0   
1          1.0      3.0       0.0       0.0       0.0       0    7        6.0   
2          1.0      5.0      30.0      30.0       1.0       0    9        4.0   
3          0.0      2.0       0.0       0.0       0.0       0   11        3.0   
4          0.0      2.0       3.0       0.0       0.0       0   11        5.0   

   Income  
0     3.0  
1     1.0  
2     8.0  
3     6.0  
4     4.0  

[5 rows x 22 columns]

In [99]:
df3 = df3.astype({'Age' : 'int' })

In [100]:
df3.head()

Age  Gender   BMI  SBP  DBP   FPG  Chol   Tri   HDL   LDL   ALT   BUN  \
0    2       0  20.1  119   81  5.80  4.36  0.86  0.90  2.43  12.0  5.40   
1    5       0  17.7   97   54  4.60  3.70  1.02  1.50  2.04   9.2  3.70   
2    5       1  19.7   85   53  5.30  5.87  1.29  1.75  3.37  10.1  4.10   
3    5       0  23.1  111   71  4.50  4.05  0.74  1.27  2.60  36.5  4.38   
4    4       0  26.5  130   82  5.54  6.69  3.49  0.91  3.64  69.3  3.86   

    CCR  FFPG  smoking  drinking  family_histroy  Diabetes  
0  63.8  5.40        0         0               0         0  
1  70.3  4.10        1         1               0         0  
2  61.1  4.85        0         0               0         0  
3  73.4  5.30        1         0               0         0  
4  67.5  5.53        0         0               0         0

In [101]:
df3['BMI'] = df3['BMI'].round(0)

In [103]:
df3.head()

Age  Gender   BMI  SBP  DBP   FPG  Chol   Tri   HDL   LDL   ALT   BUN  \
0    2       0  20.0  119   81  5.80  4.36  0.86  0.90  2.43  12.0  5.40   
1    5       0  18.0   97   54  4.60  3.70  1.02  1.50  2.04   9.2  3.70   
2    5       1  20.0   85   53  5.30  5.87  1.29  1.75  3.37  10.1  4.10   
3    5       0  23.0  111   71  4.50  4.05  0.74  1.27  2.60  36.5  4.38   
4    4       0  26.0  130   82  5.54  6.69  3.49  0.91  3.64  69.3  3.86   

    CCR  FFPG  smoking  drinking  family_histroy  Diabetes  
0  63.8  5.40        0         0               0         0  
1  70.3  4.10        1         1               0         0  
2  61.1  4.85        0         0               0         0  
3  73.4  5.30        1         0               0         0  
4  67.5  5.53        0         0               0         0

In [104]:
df.columns

Index(['Diabetes', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'smoking',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Gender', 'Age', 'Education',
       'Income'],
      dtype='object')

In [105]:
df3.columns

Index(['Age', 'Gender', 'BMI', 'SBP', 'DBP', 'FPG', 'Chol', 'Tri', 'HDL',
       'LDL', 'ALT', 'BUN', 'CCR', 'FFPG', 'smoking', 'drinking',
       'family_histroy', 'Diabetes'],
      dtype='object')

In [143]:
df_merged = pd.merge(df , df3 , on=['Age' , 'BMI' , 'smoking' , 'Gender' , 'Diabetes'] , how= 'inner')

In [141]:
df_merged.head()

Diabetes  HighBP  HighChol  CholCheck   BMI  smoking  Stroke  \
0         0     0.0       0.0        0.0  25.0        1     0.0   
1         0     0.0       0.0        0.0  25.0        1     0.0   
2         0     0.0       0.0        0.0  25.0        1     0.0   
3         0     0.0       0.0        0.0  25.0        1     0.0   
4         0     0.0       0.0        0.0  25.0        1     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  Chol   Tri   HDL   LDL  \
0                   0.0           1.0     0.0  ...  3.80  1.50  1.22  2.35   
1                   0.0           1.0     0.0  ...  3.54  0.56  1.03  2.06   
2                   0.0           1.0     0.0  ...  5.00  3.10  1.34  2.83   
3                   0.0           1.0     0.0  ...  6.61  3.87  1.16  3.71   
4                   0.0           1.0     0.0  ...  4.41  2.60  0.75  2.44   

    ALT   BUN    CCR  FFPG  drinking  family_histroy  
0  44.0  5.99  102.0  5.70         0               1  
1  14.0  7.86   78.1  5.90         0               0  
2  35.0  5.19   84.0  6.10         0               0  
3  60.8  4.19   80.3  5.55         0               0  
4  36.0  4.69   70.0  4.70         1               0  

[5 rows x 35 columns]

In [142]:
df_merged.shape

(771839, 35)

In [116]:
# Check for duplicates in the key columns in both dataframes
duplicates_df = df.duplicated(subset=['Age', 'BMI', 'smoking', 'Gender', 'Diabetes'])
duplicates_df3 = df3.duplicated(subset=['Age', 'BMI', 'smoking', 'Gender', 'Diabetes'])

print(duplicates_df.sum())  # Number of duplicate rows in df
print(duplicates_df3.sum())  # Number of duplicate rows in df3


248055
2707


In [144]:
df_merged_new = df_merged.drop_duplicates()

In [151]:
df_merged_new['FFPG'].unique()

array([ 5.7 ,  5.9 ,  6.1 ,  5.55,  4.7 ,  4.8 ,  6.08,  5.02,  5.81,
        4.91,  5.1 ,  6.6 ,  5.01,  4.92,  4.6 ,  5.47,  5.2 ,  5.39,
        6.13, 10.26,  6.38,  5.4 ,  5.31,  8.67,  6.39,  5.6 ,  5.  ,
        5.77,  9.4 ,  6.55,  5.36,  5.43,  5.16,  7.47,  5.3 ,  5.76,
        5.49,  5.5 ,  5.56,  5.34,  5.21,  4.9 ,  5.54,  5.12,  4.5 ,
        4.64,  4.95,  4.69,  5.24,  6.12,  5.94,  6.07,  5.8 ,  4.33,
        4.76,  4.99,  4.77,  6.5 ,  5.53,  5.04,  4.87,  5.45,  6.  ,
        4.65,  5.23,  5.25,  5.13,  6.9 ,  5.03,  4.74,  5.44,  5.63,
        5.32,  4.98,  5.46,  5.28,  6.47,  5.42,  6.41,  4.79,  5.71,
        4.61,  4.96,  5.52,  5.82,  4.83,  4.49,  4.3 ,  4.63,  4.71,
        6.06,  5.61,  5.62,  5.64,  5.29,  7.99,  7.1 ,  5.66,  7.59,
        4.2 ,  5.41,  5.07,  5.37,  6.7 ,  5.57,  5.51,  5.26,  5.11,
        4.94,  4.55,  5.15,  4.56,  5.88,  5.09,  5.33,  4.73,  4.4 ,
        4.82,  4.41,  5.75,  5.99,  5.48,  6.3 ,  5.06,  3.95,  6.03,
        4.89,  4.93,

In [125]:
# Concatenate both DataFrames
df_combined = pd.concat([df, df3], ignore_index=True)


In [128]:
df_combined.isnull().sum()

Diabetes                     0
HighBP                    3410
HighChol                  3410
CholCheck                 3410
BMI                          0
smoking                      0
Stroke                    3410
HeartDiseaseorAttack      3410
PhysActivity              3410
Fruits                    3410
Veggies                   3410
HvyAlcoholConsump         3410
AnyHealthcare             3410
NoDocbcCost               3410
GenHlth                   3410
MentHlth                  3410
PhysHlth                  3410
DiffWalk                  3410
Gender                       0
Age                          0
Education                 3410
Income                    3410
SBP                     253680
DBP                     253680
FPG                     253680
Chol                    253680
Tri                     253680
HDL                     253680
LDL                     253680
ALT                     253680
BUN                     253680
CCR                     253680
FFPG    

In [157]:
# Count how many rows are duplicated
duplicate_row_count = df_merged_new.duplicated().sum()

print(f"Number of duplicate rows: {duplicate_row_count}")


Number of duplicate rows: 0


In [158]:
df_merged_new.to_csv("final_dataset.csv" , index=False)

In [159]:
target_size = 200000
sampled_df = df_merged_new.groupby(['FPG', 'FFPG', 'Age', 'BMI'], group_keys=False).apply(
    lambda x: x.sample(frac=target_size / len(df_merged_new), random_state=42)
)

C:\Users\vishal ghosh\AppData\Local\Temp\ipykernel_16048\4198762804.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_df = df_merged_new.groupby(['FPG', 'FFPG', 'Age', 'BMI'], group_keys=False).apply(


In [167]:
sampled_df.columns

Index(['Diabetes', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'smoking',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Gender', 'Age', 'Education',
       'Income', 'SBP', 'DBP', 'FPG', 'Chol', 'Tri', 'HDL', 'LDL', 'ALT',
       'BUN', 'CCR', 'FFPG', 'drinking', 'family_histroy'],
      dtype='object')

In [168]:
sampled_df.to_csv("glucose_dataset.csv" , index=False)

In [169]:
sampled_df['BMI'].unique()

array([25., 28., 22., 21., 19., 18., 26., 17., 24., 23., 29., 20., 30.,
       34., 27., 36., 32., 37., 16., 35., 33., 31.])